import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Noor Mohammad</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <main className="text-xl font-bodyFont">
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Error beatae
        neque soluta hic facilis saepe sunt voluptate dolorem, temporibus esse
        nobis, nihil laboriosam possimus molestiae a quis dignissimos aperiam
        dolor delectus magni ea obcaecati! Quae non eligendi vitae distinctio
        explicabo molestiae, adipisci provident cumque obcaecati consectetur quo
        similique ab odio!
      </main>
    </>
  );
}
